# Generated by Django 5.2.3 on 2025-07-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='is_ordered',
        ),
    ]
